# Generated by Django 5.0.3 on 2024-04-03 05:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billingaddress',
            name='name',
        ),
        migrations.RemoveField(
            model_name='billingaddress',
            name='pin_code',
        ),
        migrations.AddField(
            model_name='billingaddress',
            name='country',
            field=models.CharField(default='', max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='billingaddress',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='billingaddress',
            name='firstname',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='billingaddress',
            name='lastname',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='billingaddress',
            name='zip_code',
            field=models.CharField(default='', max_length=9, validators=[django.core.validators.RegexValidator('^\\d{0,9}$')]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='billingaddress',
            name='phone_number',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator('^\\+?1?\\d{9,15}$')]),
        ),
    ]
