# Generated by Django 5.0.3 on 2024-04-03 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_billingaddress_apartment'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingaddress',
            name='street_address',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
