# Generated by Django 5.0.3 on 2024-04-03 16:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_rename_firstname_billingaddress_first_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='billingaddress',
            old_name='first_name',
            new_name='firstname',
        ),
        migrations.RenameField(
            model_name='billingaddress',
            old_name='last_name',
            new_name='lastname',
        ),
        migrations.AlterField(
            model_name='billingaddress',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='billing_addresses', to=settings.AUTH_USER_MODEL),
        ),
    ]
